// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtajx7KHQ6eJo-AMaa8G-RJ-wrV25HNpc',
    appId: '1:883792956027:web:1551cb5973bcdb38e370de',
    messagingSenderId: '883792956027',
    projectId: 'clone-c0dd1',
    authDomain: 'clone-c0dd1.firebaseapp.com',
    storageBucket: 'clone-c0dd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg30YjBKGqNxrT6dkJ_A-Q1PrbzQifzmg',
    appId: '1:883792956027:android:63281904d9c140f7e370de',
    messagingSenderId: '883792956027',
    projectId: 'clone-c0dd1',
    storageBucket: 'clone-c0dd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qExX2Q5YV3wXnnmS3JstTLOO5ZzHJpk',
    appId: '1:883792956027:ios:d304ca2344679354e370de',
    messagingSenderId: '883792956027',
    projectId: 'clone-c0dd1',
    storageBucket: 'clone-c0dd1.appspot.com',
    iosClientId: '883792956027-oklblruutpnbof648bplc206c24gcoei.apps.googleusercontent.com',
    iosBundleId: 'com.appsbymuk.amazonFirebase',
  );
}
